// Sumber: Form Audit Cleaning (Excel) - 57 indikator, 6 kategori.
// File ini dipakai sebagai default/seed. Data live dibaca dari Firestore collection `indicators`.

export type IndicatorCategoryCode =
  | 'KITCHEN'
  | 'SERVICE'
  | 'LOBBY'
  | 'STORAGE'
  | 'BACK'
  | 'PARKING';

export interface Indicator {
  id: string;
  no: number;
  categoryCode: IndicatorCategoryCode;
  category: string;
  area: string;
  standard: string;
  active: boolean;
  weight: number;
}

export const CATEGORY_ORDER: { code: IndicatorCategoryCode; label: string }[] = [
  { code: 'KITCHEN', label: 'Area Production / Kitchen' },
  { code: 'SERVICE', label: 'Area Service / Cashier' },
  { code: 'LOBBY', label: 'Area Lobby / Dining' },
  { code: 'STORAGE', label: 'Dry Storage / Cold Storage' },
  { code: 'BACK', label: 'Back Area / Utility / Outdoor' },
  { code: 'PARKING', label: 'Akses Masuk & Parking Yard' },
];

export const DEFAULT_INDICATORS: Indicator[] = [
  {
    id: 'IND-01',
    no: 1,
    categoryCode: 'KITCHEN',
    category: "Area Production / Kitchen",
    area: "Exhaust Hood",
    standard: "Bersih, tidak berminyak dan tidak berkerak. bebas lemak menumpuk; tidak ada debu. Permukaan sudut dan sambungan bebas grease; tidak ada bagian longgar atau rusak.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-02',
    no: 2,
    categoryCode: 'KITCHEN',
    category: "Area Production / Kitchen",
    area: "Kipas Angin Kitchen",
    standard: "Bersih, dan bebas debu pada cover/kisi; tidak ada bunyi, getaran, atau kerusakan abnormal.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-03',
    no: 3,
    categoryCode: 'KITCHEN',
    category: "Area Production / Kitchen",
    area: "Dinding Keramik/ Tembok Area Kitchen Bersih",
    standard: "Bersih, tidak ada debu dan tidak ada bekas lem(selotip, double tape. Bebas noda, cipratan minyak, jamur, dan bagian yang mengelupas.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-04',
    no: 4,
    categoryCode: 'KITCHEN',
    category: "Area Production / Kitchen",
    area: "Grease Trap Comp-Sink",
    standard: "Bersih, tidak tersumbat dan tidak ada lemak menggumpal. bebas. Aliran lancar, tidak berbau menyengat, tidak ada sisa makanan/lemak menumpuk, dan penutup terpasang baik.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-05',
    no: 5,
    categoryCode: 'KITCHEN',
    category: "Area Production / Kitchen",
    area: "Cup Sealer",
    standard: "Bersih dan tidak berkerak. bebas debu, noda dan sisa kotoran minuman; tidak ada kerusakan. Area sealing bebas residu minuman/plastik; permukaan tidak lengket dan kabel/plug dalam kondisi baik.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-06',
    no: 6,
    categoryCode: 'KITCHEN',
    category: "Area Production / Kitchen",
    area: "Holding Cabinet / Warmer",
    standard: "Bersih dan tidak ada debu, noda dan sisa kotoran. Rak, sudut, pintu dan handle bebas remah/grease; dan pintu menutup baik.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-07',
    no: 7,
    categoryCode: 'KITCHEN',
    category: "Area Production / Kitchen",
    area: "Kaki-kaki Meja, Roda Equipment di Area Kitchen",
    standard: "Bersih dan bebas debu, noda dan sisa makanan di bagian bawah/kaki. Roda dan sela-sela bebas grease/sisa makanan; roda dapat bergerak dan terkunci dengan baik.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-08',
    no: 8,
    categoryCode: 'KITCHEN',
    category: "Area Production / Kitchen",
    area: "Fryer, Kompor",
    standard: "Bersih dan bebas grease/lemak menumpuk; tidak ada sumbatan. Area bawah/samping bebas grease dan sisa makanan; tidak ada kebocoran gas/minyak atau bagian rusak yang terlihat.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-09',
    no: 9,
    categoryCode: 'KITCHEN',
    category: "Area Production / Kitchen",
    area: "Dinding di Belakang Fryer",
    standard: "Bersih, tidak berminyak. bebas grease/lemak menumpuk. Bebas noda, cipratan minyak, debu, bekas perekat, jamur, dan bagian yang mengelupas.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-10',
    no: 10,
    categoryCode: 'KITCHEN',
    category: "Area Production / Kitchen",
    area: "Flame Guard Exhaust",
    standard: "Bersih, tidak berminyak dan tidak berkerak. Permukaan sudut dan sambungan bebas grease; tidak ada bagian longgar atau rusak.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-11',
    no: 11,
    categoryCode: 'KITCHEN',
    category: "Area Production / Kitchen",
    area: "Rice Cooker",
    standard: "Bersih dan api tidak tersumbat. bebas debu, noda dan sisa kotoran; area burner bebas kerak/sisa nasi; api stabil dan tidak ada bau gas.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-12',
    no: 12,
    categoryCode: 'SERVICE',
    category: "Area Service / Cashier",
    area: "Poster Promosi di Area Cashier (A4)",
    standard: "Bersih, rapi dan akrilik tidak pecah. bebas debu, sidik jari dan bercak; terpasang menghadap customer, dan informasi mudah dibaca.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-13',
    no: 13,
    categoryCode: 'SERVICE',
    category: "Area Service / Cashier",
    area: "Menu Board Area Cashier",
    standard: "Bersih,dan tidak ada debu. bebas debu, sidik jari dan bercak; Lampu menu board menyala, dan informasi mudah dibaca.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-14',
    no: 14,
    categoryCode: 'SERVICE',
    category: "Area Service / Cashier",
    area: "Tembok/ Dinding Seluruh Area Cashier",
    standard: "Bersih, tidak ada debu dan tidak ada bekas lem (bekas selotip/double tape). Bebas noda, cipratan minyak dan bagian yang mengelupas.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-15',
    no: 15,
    categoryCode: 'SERVICE',
    category: "Area Service / Cashier",
    area: "Lantai area Kasir",
    standard: "Lantai bersih dan tidak ada kotoran. bebas sampah, noda, debu dan grease.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-16',
    no: 16,
    categoryCode: 'SERVICE',
    category: "Area Service / Cashier",
    area: "Lemari Rak Area Cashier",
    standard: "Rak bersih, bebas debu dan barang tersusun rapi dan tidak berlebihan.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-17',
    no: 17,
    categoryCode: 'SERVICE',
    category: "Area Service / Cashier",
    area: "Baseboard Cashier",
    standard: "Bersih dan tidak ada debu, noda dan sisa kotoran.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-18',
    no: 18,
    categoryCode: 'LOBBY',
    category: "Area Lobby / Dining",
    area: "Kaca Lobby Bagian Dalam (Seluruh Area)",
    standard: "Bersih, mengkilap dan tidak bercak. bebas debu, sidik jari. Seluruh sudut dan frame bebas debu; tidak ada bekas air, stiker atau residu lem.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-19',
    no: 19,
    categoryCode: 'LOBBY',
    category: "Area Lobby / Dining",
    area: "Kipas Angin Area Lobby",
    standard: "Bersih, dan bebas debu pada cover/kisi; tidak ada bunyi, getaran, atau kerusakan abnormal.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-20',
    no: 20,
    categoryCode: 'LOBBY',
    category: "Area Lobby / Dining",
    area: "Lampu Letter Sign & Logo",
    standard: "Bersih dan lampu tidak ada yang mati. bebas debu, tidak ada bagian retak/lepas;.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-21',
    no: 21,
    categoryCode: 'LOBBY',
    category: "Area Lobby / Dining",
    area: "Toilet",
    standard: "Closet, dinding, lantai bersih dan wangi. tidak ada noda/kerak, rambut. Flush, handle pintu dan floor drain bersih; sabun/tisu tersedia; tidak ada genangan atau bau.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-22',
    no: 22,
    categoryCode: 'LOBBY',
    category: "Area Lobby / Dining",
    area: "Air Curtain Area Lobby",
    standard: "Bersih dan tidak ada debu. bebas debu pada curtain. Air curtain tidak ada yang sobek.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-23',
    no: 23,
    categoryCode: 'LOBBY',
    category: "Area Lobby / Dining",
    area: "Seluruh Cover AC Indoor",
    standard: "Bersih dan bebas debu pada cover, tidak ada bunyi/getaran abnormal.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-24',
    no: 24,
    categoryCode: 'LOBBY',
    category: "Area Lobby / Dining",
    area: "Dustbin Lobby",
    standard: "Bersih, bebas debu, noda dan sisa kotoran; tidak ada kerusakan Bagian dalam/luar dustbin bersih dan tidak berbau.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-25',
    no: 25,
    categoryCode: 'LOBBY',
    category: "Area Lobby / Dining",
    area: "Kaca Lobby Bagian Luar (Seluruh Area)",
    standard: "Bersih, mengkilap dan tidak bercak. bebas debu, sidik jari. Seluruh sudut dan frame bebas debu; tidak ada bekas air, stiker atau residu lem.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-26',
    no: 26,
    categoryCode: 'LOBBY',
    category: "Area Lobby / Dining",
    area: "Kaki Kursi & Meja Area Lobby",
    standard: "Bersih dan bebas debu, noda dan sisa makanan. Dudukan, sandaran, sela dan kaki bebas remah/noda; tidak lengket dan tidak ada bagian longgar/rusak.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-27',
    no: 27,
    categoryCode: 'LOBBY',
    category: "Area Lobby / Dining",
    area: "Karpet Play Land Bersih",
    standard: "Bersih dan tidak ada kotoran. bebas debu dan remah, noda dan sisa kotoran; tidak ada bagian karpet yang robek.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-28',
    no: 28,
    categoryCode: 'LOBBY',
    category: "Area Lobby / Dining",
    area: "Tiang untuk menaruh balon Area Lobby",
    standard: "Bersih dan tidak ada debu. bebas debu, noda dan sisa kotoran; tidak ada kerusakan. Bebas noda, cipratan minyak, debu, bekas perekat, jamur, dan bagian yang mengelupas.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-29',
    no: 29,
    categoryCode: 'LOBBY',
    category: "Area Lobby / Dining",
    area: "Seluruh Baseboard Lobby",
    standard: "Bersih, tidak ada kotoran. bebas debu, noda. Bebas noda, cipratan minyak, debu, bekas perekat.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-30',
    no: 30,
    categoryCode: 'LOBBY',
    category: "Area Lobby / Dining",
    area: "Seluruh Baseboard Tangga",
    standard: "Bersih, tidak ada kotoran. bebas debu, noda. Bebas noda, cipratan minyak, debu, bekas perekat.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-31',
    no: 31,
    categoryCode: 'LOBBY',
    category: "Area Lobby / Dining",
    area: "Seluruh Sofa Dining Area",
    standard: "Bersih, tidak ada kotoran. bebas debu, noda. Bebas noda, cipratan minyak, debu, bekas perekat.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-32',
    no: 32,
    categoryCode: 'LOBBY',
    category: "Area Lobby / Dining",
    area: "Seluruh Window Poster",
    standard: "Poster promosi bersih dan rapi. bebas debu, sidik jari dan bercak; tidak ada yang robek.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-33',
    no: 33,
    categoryCode: 'LOBBY',
    category: "Area Lobby / Dining",
    area: "Lis Tembok Dining",
    standard: "Bersih, tidak ada debu dan tidak ada bekas lem (selotip dan double tape) dan bagian yang mengelupas.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-34',
    no: 34,
    categoryCode: 'LOBBY',
    category: "Area Lobby / Dining",
    area: "Scrub Lantai Teras Depan",
    standard: "Bersih, tidak ada kotoran. bebas sampah, noda dan grease; tidak licin. Sudut, nat dan bawah furniture/equipment bersih; lantai tidak licin, tidak lengket, dan tanpa genangan.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-35',
    no: 35,
    categoryCode: 'LOBBY',
    category: "Area Lobby / Dining",
    area: "Traffic Cone & Baby Chair",
    standard: "Bersih dan tidak ada debu. bebas debu, noda dan sisa makanan, Dudukan, sandaran, sela dan kaki bebas remah/noda; tidak lengket dan tidak ada bagian longgar/rusak.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-36',
    no: 36,
    categoryCode: 'LOBBY',
    category: "Area Lobby / Dining",
    area: "Lantai Lobby",
    standard: "Lantai bersih dan tidak ada kotoran. bebas sampah, noda, debu dan grease.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-37',
    no: 37,
    categoryCode: 'LOBBY',
    category: "Area Lobby / Dining",
    area: "Mushola & Area Wudhu",
    standard: "Bersih, dan tidak ada kotoran. tidak ada noda/kerak, rambut. Area salat, rak, keran dan drain bersih; lantai tidak licin, tidak ada genangan.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-38',
    no: 38,
    categoryCode: 'LOBBY',
    category: "Area Lobby / Dining",
    area: "Wastafel Dining",
    standard: "Bersih, sabun dan tissue tersedia. tidak ada noda/kerak; fixture berfungsi baik. Keran, drain dan area sekitar bebas kerak/noda; aliran lancar, tidak bocor.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-39',
    no: 39,
    categoryCode: 'STORAGE',
    category: "Dry Storage / Cold Storage",
    area: "Filter Udara Chiller",
    standard: "Bersih dan tidak ada debu. Filter/kisi bebas debu menyeluruh dan terpasang baik; tidak ada kerusakan atau suara abnormal.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-40',
    no: 40,
    categoryCode: 'STORAGE',
    category: "Dry Storage / Cold Storage",
    area: "Chiller Area Kitchen",
    standard: "Dinding, rak bersih dan barang tersusun rapi. rak/dinding bersih. Gasket, handle, rak dan sudut bersih; tidak ada darah/tumpahan, bau abnormal, atau bunga es; pintu menutup rapat.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-41',
    no: 41,
    categoryCode: 'STORAGE',
    category: "Dry Storage / Cold Storage",
    area: "Keranjang Ayam Di Chiller",
    standard: "Bersih, tidak ada darah ayam yang menggenang. t, lendir dan residu; tidak berbau, tidak retak.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-42',
    no: 42,
    categoryCode: 'STORAGE',
    category: "Dry Storage / Cold Storage",
    area: "Rak Dry Stock",
    standard: "Lantai bersih, tidak ada kotoran tikus dan barang tersusun rapi. Rak, sudut dan bawah rak bebas debu/tanda hama; produk tidak menyentuh lantai dan label mudah terlihat.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-43',
    no: 43,
    categoryCode: 'STORAGE',
    category: "Dry Storage / Cold Storage",
    area: "Area Dry Stock",
    standard: "Lantai bersih, tidak ada kotoran hama dan barang tersusun rapi. Rak, sudut dan bawah rak bebas debu/tanda hama; produk tidak menyentuh lantai dan label mudah terlihat.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-44',
    no: 44,
    categoryCode: 'STORAGE',
    category: "Dry Storage / Cold Storage",
    area: "Dinding Chiller",
    standard: "Bersih, dan tidak ada debu. rak/dinding bersih; tidak ada tumpahan atau bebas noda, cipratan minyak, debu, bekas perekat, jamur, dan bagian yang mengelupas.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-45',
    no: 45,
    categoryCode: 'STORAGE',
    category: "Dry Storage / Cold Storage",
    area: "Ice Blocking Freezer",
    standard: "Bersih, tidak ada kembang es berlebih. rak/dinding bersih;. Tumpahan atau bau abnormal; gasket bersih dan pintu menutup rapat.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-46',
    no: 46,
    categoryCode: 'BACK',
    category: "Back Area / Utility / Outdoor",
    area: "Seluruh AC Outdoor",
    standard: "Bersih dan tidak ada debu. bebas debu pada cover/kisi;. Kisi/cover bersih menyeluruh; tidak ada suara, getaran, atau kerusakan abnormal.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-47',
    no: 47,
    categoryCode: 'BACK',
    category: "Back Area / Utility / Outdoor",
    area: "Area TPS (Tempat Penyimpanan Sementara)",
    standard: "Lantai bersih, tidak ada kotoran tikus dan barang tersusun rapi. bebas sampah. Setiap barang berlabel/status jelas, tidak ada barang langsung di lantai.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-48',
    no: 48,
    categoryCode: 'BACK',
    category: "Back Area / Utility / Outdoor",
    area: "Dumpster Area",
    standard: "Bersih dan bebas sampah tercecer dan genangan. Bin dan lantai bebas sisa sampah/cairan; tutup berfungsi, tidak berbau menyengat.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-49',
    no: 49,
    categoryCode: 'BACK',
    category: "Back Area / Utility / Outdoor",
    area: "Gas Room",
    standard: "Bersih dan tidak ada kotoran tikus. bebas sampah tercecer. Area kering dan berventilasi; tidak ada barang mudah terbakar, kebocoran/bau gas, atau akses yang terhalang.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-50',
    no: 50,
    categoryCode: 'BACK',
    category: "Back Area / Utility / Outdoor",
    area: "Janitor",
    standard: "Bersih, bebas sampah tercecer dan genangan, peralatan kebersihan digantung. Alat bersih dan digantung pada lokasi standar; mop tidak dibiarkan basah di lantai; chemical berlabel dan tersimpan aman.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-51',
    no: 51,
    categoryCode: 'BACK',
    category: "Back Area / Utility / Outdoor",
    area: "Grating Saluran Air",
    standard: "Bersih, tidak tersumbat dan tidak ada lemak menggumpal / menumpuk. Aliran lancar, tidak berbau menyengat, tidak ada sisa makanan, dan penutup terpasang baik.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-52',
    no: 52,
    categoryCode: 'BACK',
    category: "Back Area / Utility / Outdoor",
    area: "Grease Trap Outdoor (Utama)",
    standard: "Bersih, tidak tersumbat dan tidak ada lemak menggumpal / menumpuk. Aliran lancar, tidak berbau menyengat, tidak ada sisa makanan, dan penutup terpasang baik.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-53',
    no: 53,
    categoryCode: 'BACK',
    category: "Back Area / Utility / Outdoor",
    area: "Kolong Meja Area Manager Room",
    standard: "Bersih, tidak ada kotoran/sampah, bebas debu, noda dan sisa makanan; Kabel tertata, tidak ada tanda hama, dan akses kerja tidak terhalang.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-54',
    no: 54,
    categoryCode: 'PARKING',
    category: "Akses Masuk & Parking Yard",
    area: "Signage Luar (Jalan)",
    standard: "Bersih dan lampu tidak mati. bebas debu, tidak ada bagian retak/lepas; tampilan rapi dan elegan, Bebas sidik jari/noda; material utuh, terpasang lurus, dan informasi mudah dibaca.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-55',
    no: 55,
    categoryCode: 'PARKING',
    category: "Akses Masuk & Parking Yard",
    area: "Akses Masuk & Keluar",
    standard: "Jika Terpisah, Sign/rambu masuk dan keluar harus jelas mudah dibaca, bebas debu, tidak ada bagian retak/lepas, material utuh dan terpasang lurus. Area Akses Bebas sampah, tidak terhalang barang atau kendaraan parkir.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-56',
    no: 56,
    categoryCode: 'PARKING',
    category: "Akses Masuk & Parking Yard",
    area: "Parkir Mobil",
    standard: "Terpisah dengan Motor, Sign/Rambu Parkir Mobil harus jelas mudah dibaca, utuh / tidak ada bagian retak/lepas, terpasang lurus; Terdapat Marka Parkir; Area Parkir tidak ada yang rusak atau berlubang, bebas sampah dan genangan air.",
    active: true,
    weight: 1,
  },
  {
    id: 'IND-57',
    no: 57,
    categoryCode: 'PARKING',
    category: "Akses Masuk & Parking Yard",
    area: "Parkir Motor",
    standard: "Terpisah dengan Mobil, Sign/Rambu Parkir Mobil harus jelas mudah dibaca, utuh / tidak ada bagian retak/lepas, terpasang lurus; Terdapat Marka Parkir; Area Parkir tidak ada yang rusak atau berlubang, bebas sampah dan genangan air.",
    active: true,
    weight: 1,
  },
];
